import sqlite3
import os
import random
from datetime import datetime, timedelta

# Path references
DB_PATH = os.path.join(os.path.dirname(__file__), 'sales_management.db')
SCHEMA_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'database', 'schema.sql'))

sample_products = [
    { 'name': 'Redmi Note 13', 'description': '8GB RAM, 256GB Storage, 108MP Camera', 'price': 24500, 'stock': 12, 'category': 'Smartphones', 'image_url': 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=300' },
    { 'name': 'Samsung Galaxy A15', 'description': '4GB RAM, 128GB Storage, LTE', 'price': 18500, 'stock': 5, 'category': 'Smartphones', 'image_url': 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=300' },
    { 'name': 'Oraimo FreePods 4', 'description': 'Active Noise Cancelling True Wireless Earbuds', 'price': 4500, 'stock': 25, 'category': 'Audio', 'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=300' },
    { 'name': 'Anker PowerCore 20k', 'description': '20000mAh Power Bank with 20W Power Delivery', 'price': 5500, 'stock': 0, 'category': 'Accessories', 'image_url': 'https://images.unsplash.com/photo-1609592424085-78e794967395?w=300' },
    { 'name': 'Vitron 32 inch Smart TV', 'description': 'Frameless Android Smart LED TV', 'price': 13500, 'stock': 3, 'category': 'Electronics', 'image_url': 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=300' },
    { 'name': 'Type-C Fast Charger 20W', 'description': 'Dual port wall adapter with cable', 'price': 1500, 'stock': 45, 'category': 'Accessories', 'image_url': 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=300' }
]

def get_past_date(days_ago):
    d = datetime.now() - timedelta(days=days_ago)
    return d.strftime('%Y-%m-%d %H:%M:%S')

def seed():
    print("Seeding database...")
    if not os.path.exists(SCHEMA_PATH):
        print(f"Error: Schema file not found at {SCHEMA_PATH}")
        return

    # Delete existing DB file to have a clean slate for schema migration
    if os.path.exists(DB_PATH):
        try:
            os.remove(DB_PATH)
        except Exception:
            pass

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Read schema.sql and rewrite postgres specific parts for sqlite
    with open(SCHEMA_PATH, 'r', encoding='utf-8') as f:
        schema_sql = f.read()

    # PostgreSQL to SQLite conversions
    schema_sql = schema_sql.replace('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'INTEGER PRIMARY KEY AUTOINCREMENT')
    schema_sql = schema_sql.replace('BIGINT', 'INTEGER')
    schema_sql = schema_sql.replace('NUMERIC', 'REAL')
    schema_sql = schema_sql.replace('TIMESTAMP WITH TIME ZONE', 'TEXT')
    schema_sql = schema_sql.replace('BOOLEAN DEFAULT FALSE', 'INTEGER DEFAULT 0')
    schema_sql = schema_sql.replace('IS_RECONCILED BOOLEAN', 'is_reconciled INTEGER')

    cursor.executescript(schema_sql)
    conn.commit()

    # 1. Insert Products
    for p in sample_products:
        cursor.execute("""
            INSERT INTO products (name, description, price, stock, category, image_url)
            VALUES (?, ?, ?, ?, ?, ?);
        """, (p['name'], p['description'], p['price'], p['stock'], p['category'], p['image_url']))
    conn.commit()

    # Retrieve inserted products to map IDs
    cursor.execute("SELECT id, price FROM products;")
    products_db = [{'id': r[0], 'price': r[1]} for r in cursor.fetchall()]

    # 2. Seed Sales History
    mpesa_codes = ['QHN1A7X92J', 'QIP3M8Y20K', 'QKB4P9D81L', 'QLA9Z2X74M', 'QNB5R1T63V']
    customers = [
        { 'name': 'Teddy Maitha', 'phone': '0712345678' },
        { 'name': 'Alice Wambui', 'phone': '0722112233' },
        { 'name': 'John Kamau', 'phone': '0733445566' },
        { 'name': 'Sarah Atieno', 'phone': '0799887766' }
    ]

    for i in range(25):
        days_ago = random.randint(0, 85)
        order_date = get_past_date(days_ago)
        
        customer = random.choice(customers)
        payment_method = 'M-Pesa Online' if random.random() > 0.4 else ('Cash' if random.random() > 0.5 else 'M-Pesa SMS')
        payment_status = 'Pending' if (payment_method == 'M-Pesa SMS' and random.random() > 0.6) else 'Paid'
        order_status = 'Fulfilled' if payment_status == 'Paid' else 'Pending'
        
        mpesa_code = None
        if payment_method != 'Cash' and payment_status == 'Paid':
            if mpesa_codes:
                mpesa_code = mpesa_codes.pop()
            else:
                chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
                mpesa_code = 'Q' + ''.join(random.choice(chars) for _ in range(9))

        # Select items
        num_items = random.randint(1, 2)
        selected_items = []
        total_amount = 0.0

        chosen_prods = random.sample(products_db, min(num_items, len(products_db)))
        for p in chosen_prods:
            qty = random.randint(1, 2)
            selected_items.append({ 'id': p['id'], 'price': p['price'], 'qty': qty })
            total_amount += p['price'] * qty

        cursor.execute("""
            INSERT INTO orders (customer_name, customer_phone, payment_method, payment_status, order_status, total_amount, mpesa_code, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?);
        """, (customer['name'], customer['phone'], payment_method, payment_status, order_status, total_amount, mpesa_code, order_date))
        
        order_id = cursor.lastrowid

        for item in selected_items:
            cursor.execute("""
                INSERT INTO order_items (order_id, product_id, quantity, unit_price)
                VALUES (?, ?, ?, ?);
            """, (order_id, item['id'], item['qty'], item['price']))
            
            # Deduct stock
            if payment_status == 'Paid' or order_status == 'Fulfilled':
                cursor.execute("""
                    UPDATE products SET stock = MAX(stock - ?, 0) WHERE id = ?;
                """, (item['qty'], item['id']))

    conn.commit()
    conn.close()
    print("Database seeded successfully!")

if __name__ == '__main__':
    seed()
