-- Migration: Add Soft Delete and Customer Support
-- Run this in your Supabase SQL Editor

-- 1. Add is_deleted to products table if it doesn't exist
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. Create customers table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Enable Row Level Security (RLS) on customers
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for customers
DROP POLICY IF EXISTS "Users can only see and manage their own customers" ON customers;
CREATE POLICY "Users can only see and manage their own customers" 
ON customers FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
