-- PostgreSQL Schema for Supabase Migration

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    category TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    customer_phone TEXT,
    payment_method TEXT NOT NULL, -- 'Cash', 'M-Pesa Online', 'M-Pesa SMS'
    payment_status TEXT NOT NULL DEFAULT 'Pending', -- 'Pending', 'Paid', 'Failed'
    order_status TEXT NOT NULL DEFAULT 'Pending', -- 'Pending', 'Fulfilled', 'Cancelled'
    total_amount NUMERIC NOT NULL,
    mpesa_code TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC NOT NULL,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS mpesa_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpesa_code TEXT UNIQUE NOT NULL,
    sender_name TEXT,
    sender_phone TEXT,
    amount NUMERIC NOT NULL,
    parsed_text TEXT NOT NULL,
    is_reconciled BOOLEAN DEFAULT FALSE,
    reconciled_order_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(reconciled_order_id) REFERENCES orders(id)
);
